// /* This Source Code Form is subject to the terms of the Mozilla Public
//  * License, v. 2.0. If a copy of the MPL was not distributed with this
//  * file, You can obtain one at https://mozilla.org/MPL/2.0/.
//  */

namespace TimeZones
{
	/// <summary>
	/// Represents a single geographical point.
	/// </summary>
	public class Coordinates
	{
		/// <summary>
		/// Gets or sets the latitude.
		/// </summary>
		/// <value>The latitude.</value>
		/// <autogeneratedoc />
		public double Latitude  { get; set; }
		/// <summary>
		/// Gets or sets the longitude.
		/// </summary>
		/// <value>The longitude.</value>
		/// <autogeneratedoc />
		public double Longitude { get; set; }

		/// <summary>
		/// Parses the specified text to extract valid coordinates from any of the following formats:<br/>
		/// <list type="bullet">
		/// <item>Decimal: 41.5057367,-81.6945422</item>
		/// <item>Decimal &amp; Ordinal (Abbreviated): 41.5057367 N, 81.6945422 W</item>
		/// <item>Decimal &amp; Ordinal: 41.5057367 North, 81.6945422 West</item>
		/// <item>Degrees, Minutes: 41° 30' 20.6532",-81° 41' 40.3506"</item>
		/// <item>Degrees, Minutes: 41° 30' 20.6532",-81° 41' 40.3506"</item>
		/// <item>Degrees, Minutes &amp; Ordinal (Abbreviated): 41° 30' 20.6532" N, 81° 41' 40.3506" W</item>
		/// <item>Degrees, Minutes &amp; Ordinal: 41° 30' 20.6532" North, 81° 41' 40.3506" West</item>
		/// </list>
		/// </summary>
		/// <param name="text">A textual representation of geographical coordinates.</param>
		/// <returns>Coordinates.</returns>
		public static Coordinates Parse(string text)
		{
			return new Coordinates { };
		}

		/// <summary>
		/// Performs an implicit conversion to <see cref="Coordinates"/> from text in one of the following formats:<br/>
		/// <list type="bullet">
		/// <item>Decimal: 41.5057367,-81.6945422</item>
		/// <item>Decimal &amp; Ordinal (Abbreviated): 41.5057367 N, 81.6945422 W</item>
		/// <item>Decimal &amp; Ordinal: 41.5057367 North, 81.6945422 West</item>
		/// <item>Degrees, Minutes: 41° 30' 20.6532",-81° 41' 40.3506"</item>
		/// <item>Degrees, Minutes: 41° 30' 20.6532",-81° 41' 40.3506"</item>
		/// <item>Degrees, Minutes &amp; Ordinal (Abbreviated): 41° 30' 20.6532" N, 81° 41' 40.3506" W</item>
		/// <item>Degrees, Minutes &amp; Ordinal: 41° 30' 20.6532" North, 81° 41' 40.3506" West</item>
		/// </list>
		/// </summary>
		/// <param name="text">A textual representation of geographical coordinates.</param>
		/// <returns>Coordinates.</returns>
		public static implicit operator Coordinates(string text)
		{
			return Parse(text);
		}
	}

}