using System;

namespace TimeZones
{
	/// <summary>
	/// Class Finder.
	/// Implements the <see cref="TimeZones.IFindTimeZones" />
	/// </summary>
	/// <seealso cref="TimeZones.IFindTimeZones" />
	/// <autogeneratedoc />
	public class Finder : IFindTimeZones
	{
		/// <summary>
		/// Finds the time zone.
		/// </summary>
		/// <param name="coordinates">The coordinates.</param>
		/// <returns>Zone.</returns>
		/// <exception cref="NotImplementedException"></exception>
		/// <autogeneratedoc />
		public Zone FindTimeZone(Coordinates coordinates)
		{
			throw new NotImplementedException();
		}
	}

	/// <summary>
	/// Interface IFindTimeZones
	/// </summary>
	/// <autogeneratedoc />
	public interface IFindTimeZones
	{
		/// <summary>
		/// Finds the time zone.
		/// </summary>
		/// <param name="coordinates">The coordinates.</param>
		/// <returns>Zone.</returns>
		/// <autogeneratedoc />
		Zone FindTimeZone(Coordinates coordinates);
	}
}
