using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TimeZones
{
	/// <summary>
	/// Class Zone.
	/// </summary>
	/// <autogeneratedoc />
	public class Zone
	{
		/// <summary>
		/// Gets or sets the name.
		/// </summary>
		/// <value>The name.</value>
		/// <autogeneratedoc />
		public string Name { get; set; } = string.Empty;

		/// <summary>
		/// Parses the specified name.
		/// </summary>
		/// <param name="name">The name.</param>
		/// <returns>Zone.</returns>
		/// <autogeneratedoc />
		public static Zone Parse(string name)
		{
			return new Zone
			{
				Name = name,
			};
		}

		/// <summary>
		/// Performs an implicit conversion from <see cref="System.String"/> to <see cref="Zone"/>.
		/// </summary>
		/// <param name="name">The name.</param>
		/// <returns>The result of the conversion.</returns>
		/// <autogeneratedoc />
		public static implicit operator Zone(string name)
		{
			return Parse(name);
		}
	}
}
